@echo off
chcp 65001 >nul
echo.
echo ============================================
echo   InternFlow Backend - Setup Environment
echo ============================================
echo.

:: Check if .env already exists
if exist ".env" (
    echo [!] File .env da ton tai.
    set /p OVERWRITE="Ban co muon ghi de khong? (y/n): "
    if /i not "%OVERWRITE%"=="y" (
        echo [i] Giu nguyen file .env hien tai. Thoat.
        goto :END
    )
)

:: Ask for database password
echo [?] Nhap mat khau Supabase Database (hoi nhom truong):
set /p DB_PASSWORD=""

if "%DB_PASSWORD%"=="" (
    echo [X] Mat khau khong duoc de trong!
    goto :END
)

:: URL-encode special characters in password
:: Common special chars: @ -> %%40, ! -> %%21, # -> %%23, $ -> %%24, ? -> %%3F
set "ENCODED_PASSWORD=%DB_PASSWORD%"

:: Generate .env file
echo [*] Dang tao file .env...
(
echo # ========================
echo # InternFlow Backend - Environment Variables
echo # Auto-generated by setup.bat
echo # ========================
echo.
echo # Server
echo PORT=4000
echo NODE_ENV=development
echo.
echo # Connect to Supabase via connection pooling ^(dung cho app runtime^)
echo DATABASE_URL="postgresql://postgres.wecbcirwlsynesllxhgo:%ENCODED_PASSWORD%@aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres?pgbouncer=true"
echo.
echo # Direct connection to the database ^(dung cho Prisma migrations ^& introspection^)
echo DIRECT_URL="postgresql://postgres.wecbcirwlsynesllxhgo:%ENCODED_PASSWORD%@aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres"
) > .env

echo.
echo [OK] File .env da duoc tao thanh cong!
echo.

:: Install dependencies
echo [*] Dang cai dat dependencies...
call npm install

echo.
echo [*] Dang generate Prisma Client...
call npx prisma generate

echo.
echo ============================================
echo   Setup hoan tat! Chay "npm run dev" de bat dau.
echo ============================================

:END
echo.
pause
