#!/bin/bash

echo ""
echo "============================================"
echo "  InternFlow Backend - Setup Environment"
echo "============================================"
echo ""

# Check if .env already exists
if [ -f ".env" ]; then
    echo "[!] File .env đã tồn tại."
    read -p "Bạn có muốn ghi đè không? (y/n): " OVERWRITE
    if [ "$OVERWRITE" != "y" ] && [ "$OVERWRITE" != "Y" ]; then
        echo "[i] Giữ nguyên file .env hiện tại. Thoát."
        exit 0
    fi
fi

# Ask for database password
echo "[?] Nhập mật khẩu Supabase Database (hỏi nhóm trưởng):"
read -s DB_PASSWORD
echo ""

if [ -z "$DB_PASSWORD" ]; then
    echo "[X] Mật khẩu không được để trống!"
    exit 1
fi

# Generate .env file
echo "[*] Đang tạo file .env..."
cat > .env << EOF
# ========================
# InternFlow Backend - Environment Variables
# Auto-generated by setup.sh
# ========================

# Server
PORT=4000
NODE_ENV=development

# Connect to Supabase via connection pooling (dùng cho app runtime)
DATABASE_URL="postgresql://postgres.wecbcirwlsynesllxhgo:${DB_PASSWORD}@aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres?pgbouncer=true"

# Direct connection to the database (dùng cho Prisma migrations & introspection)
DIRECT_URL="postgresql://postgres.wecbcirwlsynesllxhgo:${DB_PASSWORD}@aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres"
EOF

echo ""
echo "[✓] File .env đã được tạo thành công!"
echo ""

# Install dependencies
echo "[*] Đang cài đặt dependencies..."
npm install

echo ""
echo "[*] Đang generate Prisma Client..."
npx prisma generate

echo ""
echo "============================================"
echo "  Setup hoàn tất! Chạy 'npm run dev' để bắt đầu."
echo "============================================"
