/**
 * InternFlow Backend - Interactive Setup Script
 * Chạy: npm run setup
 * 
 * Script này sẽ hỏi mật khẩu database và tự tạo file .env
 */

const readline = require('readline');
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

const ENV_PATH = path.join(__dirname, '..', '.env');

// Supabase project config (chỉ thiếu password)
const PROJECT_REF = 'wecbcirwlsynesllxhgo';
const REGION = 'aws-1-ap-northeast-1';

function generateEnvContent(password) {
  return `# ========================
# InternFlow Backend - Environment Variables
# Auto-generated by: npm run setup
# ========================

# Server
PORT=4000
NODE_ENV=development

# Connect to Supabase via connection pooling (dùng cho app runtime)
DATABASE_URL="postgresql://postgres.${PROJECT_REF}:${password}@${REGION}.pooler.supabase.com:6543/postgres?pgbouncer=true"

# Direct connection to the database (dùng cho Prisma migrations & introspection)
DIRECT_URL="postgresql://postgres.${PROJECT_REF}:${password}@${REGION}.pooler.supabase.com:5432/postgres"
`;
}

function askQuestion(question) {
  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      resolve(answer.trim());
    });
  });
}

async function main() {
  console.log('');
  console.log('============================================');
  console.log('  InternFlow Backend - Setup Environment');
  console.log('============================================');
  console.log('');

  // Check if .env exists
  if (fs.existsSync(ENV_PATH)) {
    const overwrite = await askQuestion('[!] File .env đã tồn tại. Ghi đè? (y/n): ');
    if (overwrite.toLowerCase() !== 'y') {
      console.log('[i] Giữ nguyên file .env hiện tại. Thoát.');
      rl.close();
      return;
    }
  }

  // Ask for password
  const password = await askQuestion('[?] Nhập mật khẩu Supabase Database (hỏi nhóm trưởng): ');

  if (!password) {
    console.log('[✗] Mật khẩu không được để trống!');
    rl.close();
    process.exit(1);
  }

  // Write .env
  console.log('[*] Đang tạo file .env...');
  fs.writeFileSync(ENV_PATH, generateEnvContent(password), 'utf-8');
  console.log('[✓] File .env đã được tạo thành công!');
  console.log('');

  // Generate Prisma client
  console.log('[*] Đang generate Prisma Client...');
  try {
    execSync('npx prisma generate', { stdio: 'inherit', cwd: path.join(__dirname, '..') });
    console.log('[✓] Prisma Client đã generate thành công!');
  } catch (err) {
    console.log('[!] Lỗi khi generate Prisma Client. Hãy chạy lại: npx prisma generate');
  }

  console.log('');
  console.log('============================================');
  console.log('  ✅ Setup hoàn tất! Chạy "npm run dev"');
  console.log('============================================');
  console.log('');

  rl.close();
}

main();
